---
title: "Data Source"
output:  html_document
---

# **Why NSDUH 2019**

To study the association between marijuana use and mental health, we used data from the 2019 National Survey on Drug Use and Health ([NSDUH](https://nsduhweb.rti.org/respweb/homepage.cfm)). This nationwide study is sponsored by the Center for Behavioral Health Statistics and Quality within the Substance Abuse and Mental Services Administration (SAMHSA) and is performed annually. It collects up-to-date information on tobacco, alcohol, drug use, mental health and other health-related issues in the general population in the US. Every year, NSDUH interviews approximately 70,000 people aged 12 and older. Based on the data collected, NSDUH aims to :

* understand patterns and track trends in tobacco, alcohol and substance use in the US
* identify high-risk groups for substance use and mental health disparities
* evaluate associations between substance use and mental health burdens
* provide directions for future drug prevention, treatment, and research designs

<br>
We picked the 2019 NSDUH, since it is the newest published version besides the 2020 data. Due to the COVID-19 pandemic, SAMHSA suspended in-person data collection on the 2020 NSDUH on March 16, 2020. For the purpose of data collection, a small-scale in-person data collection was conducted in selected counties of two states from July 16 to July 22, 2020, with approval. Also, on September 11, 2020, SAMHSA approved a web-based survey. As NSDUH claimed, in-person and web-based data collections yielded differences in response and non-response patterns. Consequently, we highly question the representativity of the 2020 data. **We believe the 2019 data can give us a more accurate and comprehensive idea about the prevalence and association between marijuana use and mental health.**
<br>

We will attach the used 2019 code book below. The dataset is downloadable in various forms, including SAS, STATA, R etc. Click [here.](https://www.datafiles.samhsa.gov/dataset/national-survey-drug-use-and-health-2019-nsduh-2019-ds0001)

<iframe src ="file/NSDUH_2019_codebook.pdf" width="50%" height="500px">
