---
title: "Proposal"
author: Fengdi Zhang (fz2328); 
        Tianyou Wang (tw2838);
        Qiaoyi Xu (qx2222);  
        Chaoqun Zhou (cz2689)  
output: github_document
---

### The tentative project title
Marijuana Use and Mental Health
<br>

### The motivation for this project
There are around 48 million people in US using marijuana, and it could lead to various health impacts. Marijuana use has been causing significant social impacts and attracting a vast amount of public attention as more and more states are initiating the process of legalizing marijuana use. The legality of marijuana use still remains controversial in the US. Each state has their own restrictions on their marijuana laws for both medical and recreational uses. Based on data from the “World Population Review,” by July 2022, there are 14 states that have fully legalized the use of marijuana. In this project, we will evaluate the association among marijuana use and mental health burdens, and we would like to propose recommendations for future studies and policies.
<br>

### The intended final products
We will include 6 tabes in our final website: Welcome page, Background and Descriptive analysis, Association (statistical outputs), Further Steps, Report, Screencast. 
<br>

### The anticipated data sources
Our data comes from National survey on Drug Use and Health 2002-2019. 
<br>

### The planned analyses / visualizations / coding challenges

* We will run regression on marijuana and a few mental health issue (e.g. depression, suscidal thoughts, schizophrenia, anxiety). And perfrom hypothesis testing.  
* We will make plots showing the trend of reported marjuana use change over time. And we will have interactive plots showing the current legalization status of U.S. states, such as map showing the legality states of marijuana.  
* We might have issue with dealing with missing value in terms of analysis our data. In addition, we might have issue of merging data set from different source to create our report.
 
 
### The planned timeline (by the given data, tasks should be finished.)

Date          | Planned tasks
------------- | -------------
11/9          | Proposal due 
11/16         | Finalize dataset and analysis plan (maybe descriptive summaries
11/23         | Thanksgiving (meet online, discuss coding challenges)
11/30         | Finish coding for data analysis
12/7          | Draft websites and report done
12/10         | Finalize the report, website; record the screencast




