---
title: "mapping"
author: "Qiaoyi Xu"
date: "2022-12-06"
output:  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(usmap)
library(ggplot2)
require(maps)
library(ggrepel)
```


```{r}
legal_state = read_csv("data/legalization_state.csv") 

legal_state = legal_state %>% 
  rename(full = State)

legal_state = legal_state %>%
  mutate(status = case_when(
    Recreational == "Yes" & Medical == "Yes" ~ "Recreational/Medical", #rec/med
    Recreational == "No" & Medical == "Yes" ~ "Medical", #medical legal
    Recreational == "No" & Medical == "No" ~ "None"#none
  )) 

legal_state
```



```{r}
data(statepop)

mapping_df <-inner_join(statepop, legal_state, by = "full")

mapping_df <- mapping_df %>%
  select(-pop_2015) %>%
  mutate(status = factor(status))

labels = usmapdata::centroid_labels("states")
state_labels <- merge(mapping_df, labels, by = "fips")

plot_usmap(regions = "states", data=mapping_df, values = "status",labels = TRUE)+ 
  theme(panel.background = element_rect(colour = "black")) +
  scale_fill_manual(values = c(`Recreational/Medical` = "red", `Medical` = "blue", `None` = "grey" ), name = "Legalized states") + 
  theme(legend.position = "bottom", ) +
  labs(title = "Where marijuana is legal in the United States")

```

```{r}
plot_usmap(regions = "states", data=mapping_df, values = "status")+ 
  ggrepel::geom_label_repel(data = labels,
             aes(x = x, y = y, label = abbr),
             size = 3, alpha = 0.8,
             label.r = unit(0.5, "lines"), label.size = 0.5,
             segment.color = "red", segment.size = 1,
             seed = 1002) +
  theme(panel.background = element_rect(colour = "black")) +
  scale_fill_manual(values = c(`Recreational/Medical` = "red", `Medical` = "blue", `None` = "grey" ), name = "Legalized states") + 
  theme(legend.position = "bottom", ) +
  labs(title = "Where marijuana is legal in the United States")
```

```{r}
legalized_table <- 
  legal_state%>% 
  select(-Recreational, -Medical) %>% 
  rename(c( "States" = "full",  "Recreational legalized year" = "Year_legalized_REC", "Medical legalized year" = "Year_legalized_MED", "Legalization" = "status")
  ) %>% 
  knitr::kable()

legalized_table
```

add population into the map:
https://cran.r-project.org/web/packages/usmap/vignettes/advanced-mapping.html

https://bhaskarvk.github.io/user2017.geodataviz/notebooks/03-Interactive-Maps.nb.html 


```{r, echo=FALSE, eval=FALSE}

basic_map = ggplot() + 
  geom_polygon( data=MainStates, aes(x=long, y=lat, group=group),
                color="black", fill="lightblue" )

basic_map
```


mapping_df <-inner_join(MainStates, legal_state, by = "region") #更改每个州名字的格式


